# Generated by Django 5.1.6 on 2025-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size')], default='color', max_length=50),
        ),
    ]
