# Generated by Django 5.1.6 on 2025-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('best_seller', 'Best Seller'), ('casual_wear', 'Casual Wear'), ('wedding_wear', 'Wedding Wear'), ('sarees', 'Sarees'), ('kurtas', 'Kurtas')], default='new_arrival', max_length=50),
        ),
    ]
